# cotire.cmake 1.8.0 generated file
# /home/krash/works/devilutionX/build32/devilution_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/krash/works/devilutionX/CMake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "ASIO_STANDALONE;_DEBUG;MINIWIN;FASTER;RESOLUTION_1366x768")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "-m32;-g;-Og;-fno-omit-frame-pointer;-fsanitize=address;-fsanitize-recover=address;-fpermissive;-Wno-write-strings;-Wno-multichar;-fno-aggressive-loop-optimizations;-fno-strict-aliasing;-std=c++14")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/krash/works/devilutionX")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "/usr/include/SDL2;/home/krash/works/devilutionX/.;/home/krash/works/devilutionX/Stub;/home/krash/works/devilutionX/3rdParty/asio/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "Source/appfat.cpp;Source/automap.cpp;Source/codec.cpp;Source/control.cpp;Source/cursor.cpp;Source/dead.cpp;Source/debug.cpp;Source/diablo.cpp;Source/doom.cpp;Source/drlg_l1.cpp;Source/drlg_l2.cpp;Source/drlg_l3.cpp;Source/drlg_l4.cpp;Source/dthread.cpp;Source/effects.cpp;Source/encrypt.cpp;Source/engine.cpp;Source/error.cpp;Source/gamemenu.cpp;Source/gendung.cpp;Source/gmenu.cpp;Source/help.cpp;Source/interfac.cpp;Source/inv.cpp;Source/items.cpp;Source/lighting.cpp;Source/loadsave.cpp;Source/mainmenu.cpp;Source/minitext.cpp;Source/missiles.cpp;Source/monster.cpp;Source/mpqapi.cpp;Source/msgcmd.cpp;Source/msg.cpp;Source/multi.cpp;Source/nthread.cpp;Source/objects.cpp;Source/pack.cpp;Source/palette.cpp;Source/path.cpp;Source/pfile.cpp;Source/player.cpp;Source/plrmsg.cpp;Source/portal.cpp;Source/quests.cpp;Source/render.cpp;Source/scrollrt.cpp;Source/setmaps.cpp;Source/sha.cpp;Source/spells.cpp;Source/stores.cpp;Source/sync.cpp;Source/textdat.cpp;Source/themes.cpp;Source/tmsg.cpp;Source/town.cpp;Source/towners.cpp;Source/track.cpp;Source/trigs.cpp;Source/wave.cpp;3rdParty/PKWare/explode.cpp;3rdParty/PKWare/implode.cpp;Stub/capture.cpp;Stub/dx.cpp;Stub/fault.cpp;Stub/init.cpp;Stub/miniwin.cpp;Stub/miniwin_io.cpp;Stub/miniwin_msg_sdl.cpp;Stub/miniwin_rand.cpp;Stub/miniwin_thread.cpp;Stub/movie.cpp;Stub/restrict.cpp;Stub/sound.cpp;Stub/storm.cpp;Stub/storm_net.cpp;Stub/dvlnet/loopback.cpp;Stub/dvlnet/packet.cpp;Stub/dvlnet/base.cpp;Stub/dvlnet/udp_p2p.cpp;Stub/DiabloUI/credits.cpp;Stub/DiabloUI/diabloui.cpp;Stub/DiabloUI/dialogs.cpp;Stub/DiabloUI/mainmenu.cpp;Stub/DiabloUI/progress.cpp;Stub/DiabloUI/selconn.cpp;Stub/DiabloUI/selgame.cpp;Stub/DiabloUI/selhero.cpp;Stub/DiabloUI/title.cpp;3rdParty/StormLib/src/FileStream.cpp;3rdParty/StormLib/src/SBaseCommon.cpp;3rdParty/StormLib/src/SBaseFileTable.cpp;3rdParty/StormLib/src/SBaseSubTypes.cpp;3rdParty/StormLib/src/SCompression.cpp;3rdParty/StormLib/src/SFileExtractFile.cpp;3rdParty/StormLib/src/SFileFindFile.cpp;3rdParty/StormLib/src/SFileGetFileInfo.cpp;3rdParty/StormLib/src/SFileOpenArchive.cpp;3rdParty/StormLib/src/SFileOpenFileEx.cpp;3rdParty/StormLib/src/SFileReadFile.cpp;Stub/main.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Debug")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "6.5.0")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
