# cotire.cmake 1.8.0 generated file
# /home/krash/works/devilutionX/build32/devilution_C_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/krash/works/devilutionX/CMake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "ASIO_STANDALONE;_DEBUG;MINIWIN;FASTER;RESOLUTION_1366x768")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "-m32;-g;-fpermissive;-Wno-write-strings;-Wno-multichar;-fno-aggressive-loop-optimizations;-fno-strict-aliasing")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug")
set (COTIRE_TARGET_C_COMPILER_LAUNCHER "COTIRE_TARGET_C_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/krash/works/devilutionX")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "/usr/include/SDL2;/home/krash/works/devilutionX/.;/home/krash/works/devilutionX/Stub;/home/krash/works/devilutionX/3rdParty/asio/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "C")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "3rdParty/libsmacker/smk_bitstream.c;3rdParty/libsmacker/smk_hufftree.c;3rdParty/libsmacker/smacker.c")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Debug")
set (CMAKE_C_COMPILER_ID "GNU")
set (CMAKE_C_COMPILER_VERSION "6.5.0")
set (CMAKE_C_COMPILER "/usr/bin/cc")
set (CMAKE_C_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_C "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_C "-isystem ")
set (CMAKE_C_SOURCE_FILE_EXTENSIONS "c;m")
